language: node_js
node_js:
- '0.10'
deploy:
  provider: s3
  access_key_id: AKIAI5CJFDHOABTRCGZA
  secret_access_key:
    secure: o1fvKjqoIY0YWy6C2/EOOFQTh9XNC910n6+iLypO+1JpCJ6vWyzTC81NQMql+VEZcSqM3ntx/fXmwZRTK2jaCr3nFYlB9LyWcM4pHYQxxX38G6kA0YAYgKlrwskvNcUdQcixc7IeHeDlyqf3vTaHKW5qfvohXuMUteZayn5med8=
  bucket: personas.webmakerprototypes.org
  local-dir: build
  skip_cleanup: true
  on:
    branch: master
    repo: mozilla/webmaker-personas
